# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpagecse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='room_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
