# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpagecse', '0002_faculty_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='photo',
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(default='DEFAULT VALUE', max_length=300),
        ),
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='username',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=300),
        ),
    ]
