# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpagecse', '0008_auto_20171111_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='room_no',
            field=models.CharField(max_length=20),
        ),
    ]
