# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpagecse', '0012_education_research_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
