# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpagecse', '0014_auto_20171115_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(default='static/imagefac/def.jpg', upload_to='static/imagefac/'),
        ),
    ]
