# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpagecse', '0019_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(default='facimages/default.jpg', upload_to='facimages'),
        ),
    ]
