# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpagecse', '0020_auto_20171118_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
